owner: xtexChooser
repo: uptime

sites:
  - name: "xtex's Home"
    url: https://xtexx.eu.org
  - name: "xtex's Blog"
    url: https://blog.xtexx.eu.org
  - name: "xtex's Uptime"
    url: https://uptime.xtexx.eu.org
  - name: "xtex's Upptime"
    url: https://upptime.xtexx.eu.org
  - name: Xensor V Network IdM
    url: https://id.xvnet.eu.org
  - name: Xensor V Wiki
    url: https://w.xvnet.eu.org
  - name: Xens Meta Wiki
    url: https://meta.w.xvnet.eu.org
  - name: FLCC Wiki
    url: https://hgdns.ren
  - name: Xensor V Network ntfy
    url: https://ntfy.xvnet.eu.org
  - name: Project Archive
    url: https://lakeus.xyz
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Wikitech
    url: https://wikitech.wikimedia.org

status-website:
  cname: upptime.xtexx.eu.org
  baseUrl: /
  logoUrl: https://xtexx.eu.org/avatar.webp
  name: "xtex's Upptime"
  introTitle: "Some service statuses"
  theme: night
  scripts:
    - src: https://xtex.codeberg.page/gadgets/@main/misc/upptime-rp.js
  metaTags:
    - name: "color-scheme"
      content: "dark"
    - name: "robots"
      content: "noindex"
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://xtexx.eu.org

assignees:
  - xtexChooser

user-agent: github.com/xtexChooser/uptime
