owner: xtexChooser
repo: uptime

sites:
  - name: Xensor V Wiki
    url: https://w.xvnet.eu.org
  - name: Xens Meta Wiki
    url: https://meta.w.xvnet.eu.org
  - name: Xensor V Network ntfy
    url: https://ntfy.xvnet.eu.org
  - name: Project Archive
    url: https://lakeus.xyz
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Wikitech
    url: https://wikitech.wikimedia.org

status-website:
  cname: uptime.xtexx.eu.org
  baseUrl: /
  logoUrl: https://xtexx.eu.org/avatar.webp
  name: "xtex's Uptime"
  introTitle: "Some service statuses"
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://xtexx.eu.org

assignees:
  - xtexChooser

user-agent: github.com/xtexChooser/uptime
